/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadnacional;

import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author andre
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        JMenuBar = new javax.swing.JMenuBar();
        JMenuArchivo = new javax.swing.JMenu();
        JMenuSalir = new javax.swing.JMenuItem();
        JMenuPitagoras = new javax.swing.JMenu();
        JMenuCalcularPitagoras = new javax.swing.JMenuItem();
        JMenuOhm = new javax.swing.JMenu();
        JMenuCalcularVoltaje = new javax.swing.JMenuItem();
        JMenuCalcularCorriente = new javax.swing.JMenuItem();
        JMenuAcercaDe = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad Nacional de Colombia");

        dp.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        JMenuArchivo.setText("Archivo");

        JMenuSalir.setText("Salir");
        JMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuSalirActionPerformed(evt);
            }
        });
        JMenuArchivo.add(JMenuSalir);

        JMenuBar.add(JMenuArchivo);

        JMenuPitagoras.setText("Pitagoras");

        JMenuCalcularPitagoras.setText("Calcular Pitagoras");
        JMenuCalcularPitagoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCalcularPitagorasActionPerformed(evt);
            }
        });
        JMenuPitagoras.add(JMenuCalcularPitagoras);

        JMenuBar.add(JMenuPitagoras);

        JMenuOhm.setText("Ohm");

        JMenuCalcularVoltaje.setText("Calcular voltaje");
        JMenuCalcularVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCalcularVoltajeActionPerformed(evt);
            }
        });
        JMenuOhm.add(JMenuCalcularVoltaje);

        JMenuCalcularCorriente.setText("Calcular corriente");
        JMenuCalcularCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCalcularCorrienteActionPerformed(evt);
            }
        });
        JMenuOhm.add(JMenuCalcularCorriente);

        JMenuBar.add(JMenuOhm);

        JMenuAcercaDe.setText("Acerca de");

        jMenuItem5.setText("Acerca de");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        JMenuAcercaDe.add(jMenuItem5);

        JMenuBar.add(JMenuAcercaDe);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JMenuSalirActionPerformed

    private void JMenuCalcularPitagorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCalcularPitagorasActionPerformed
         // TODO add your handling code here:
         frmPitagoras pitagoras = new frmPitagoras();
         dp.add(pitagoras);
         pitagoras.setClosable(true);
         pitagoras.setVisible(true);
        
    }//GEN-LAST:event_JMenuCalcularPitagorasActionPerformed

    private void JMenuCalcularVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCalcularVoltajeActionPerformed
        // TODO add your handling code here:
        frmVoltaje voltaje = new frmVoltaje();
         dp.add(voltaje);
         voltaje.setClosable(true);
         voltaje.setVisible(true);
    }//GEN-LAST:event_JMenuCalcularVoltajeActionPerformed

    private void JMenuCalcularCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCalcularCorrienteActionPerformed
        // TODO add your handling code here:
        frmCorriente corriente = new frmCorriente();
         dp.add(corriente);
         corriente.setClosable(true);
         corriente.setVisible(true);
    }//GEN-LAST:event_JMenuCalcularCorrienteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         frmAcercade acercade = new frmAcercade();
         dp.add(acercade);
         acercade.setClosable(true);
         acercade.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAcercaDe;
    private javax.swing.JMenu JMenuArchivo;
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenuItem JMenuCalcularCorriente;
    private javax.swing.JMenuItem JMenuCalcularPitagoras;
    private javax.swing.JMenuItem JMenuCalcularVoltaje;
    private javax.swing.JMenu JMenuOhm;
    private javax.swing.JMenu JMenuPitagoras;
    private javax.swing.JMenuItem JMenuSalir;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
